import Head from "next/head";
import Homepage from "./homepage";
import { auth } from "../firebase/firebaseApp";
import { onAuthStateChanged } from "firebase/auth";
import { useEffect, useState } from "react";

export default function Home({ data }) {
  // set an initial state for the user
  const [user, setUser] = useState({});

  useEffect(() => {
    // check for any changes in the user's authentication state
    onAuthStateChanged(auth, (currentUser) => {
      // update the user state with the current user
      setUser(currentUser);
    });
    return () => {};
  });

  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Montserrat:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="font overflow-x-hidden">
        <Homepage user={user} trend={data.meals} />
      </main>
    </>
  );
}

// get ServerSideProps runs during the build time and does server side rendering meaning it fetches all the
// data from the database and returns it as props during build phase.

export async function getServerSideProps() {
  // making a GET request to the themealdb API Endpoint
  const res = await fetch(
    "https://www.themealdb.com/api/json/v1/1/filter.php?a=Indian"
  );
  const data = await res.json(); // parse the response as JSON
  return { props: { data } }; // return the data as props for the component to use
}
