import Head from "next/head";
import { db, initFirebase } from "../firebase/firebaseApp";
import { collection, addDoc, getDocs, query, where } from "firebase/firestore";
import {
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
  onAuthStateChanged,
} from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { useEffect, useState } from "react";
import Signin from "./signin";
import Homepage from "./homepage";

export default function Home({ posts }) {
  const auth = getAuth();

  const [user, setUser] = useState({});

  useEffect(() => {
    onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
    });
    return () => {};
  });

  return (
    <>
      <Head>
        <title>Foode -Order your meal online-</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Montserrat:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik+Mono+One&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font overflow-x-hidden">
        {user ? <Homepage user={user} trend={posts} /> : <Signin />}
      </main>
    </>
  );
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch(
    "https://www.themealdb.com/api/json/v1/1/filter.php?a=Indian"
  );
  const data = await res.json();
  return { posts: data };
};
